server:
  port: 8888
  servlet:
    context-path: /api
spring:
  application:
    name: velacorp-assignment
  datasource:
    url: jdbc:postgresql://localhost:5432/cms
    password: 123@123aA
    driver-class-name: org.postgresql.Driver
    username: postgres
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
    jpa:
      generate-ddl: false
      hibernate.ddl-auto: none
      open-in-view: false
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          jdbc.batch_size: 1000
          order_inserts: true

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
logging:
  level:
    root: info
  config: classpath:log4j2.xml