create schema if not exists assignment;

SET search_path TO assignment;

create table if not exists products
(
    id             bigint generated by default as identity
    constraint products_pk
    primary key,
    name           varchar(255)   not null,
    description    text,
    price          numeric(10, 2) not null,
    stock_quantity integer        not null
    );

alter table products
    owner to velacorp;

create table if not exists orders
(
    id            bigint generated by default as identity
    constraint orders_pk
    primary key,
    order_date    date         not null,
    customer_name varchar(255) not null,
    address       varchar(255),
    email         varchar(255),
    phone_number  varchar(20),
    status        varchar(20)  not null,
    total_amount  numeric(10, 2)
    );

alter table orders
    owner to velacorp;

create table if not exists order_details
(
    id         bigint generated by default as identity
    constraint order_details_pk
    primary key,
    order_id   bigint         not null
    constraint order_details_orders_id_fk
    references assignment.orders,
    product_id bigint         not null
    constraint order_details_products_id_fk
    references assignment.products,
    quantity   integer        not null,
    unit_price numeric(10, 2) not null
    );

alter table order_details
    owner to velacorp;

